# Generated by Django 2.0.2 on 2018-02-24 03:55

import csv_web_app_server.file_upload.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', validators=[csv_web_app_server.file_upload.validators.import_csv_file_validator])),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
