# Generated by Django 2.0.2 on 2018-02-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Csv_Upload',
            new_name='CsvUpload',
        ),
    ]
